version: "3"

services:
  spark-master:
    container_name: spark-master
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-master
      - SPARK_DRIVER_MEMORY=8G
      - KAFKA_TOPIC_NAME=streaming
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - "8000:8000"
      - "8090:8080"
      - "7077:7077"
      - "4040:4040"
      - "5000:5000"
    expose:
      - "7077"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/spark/spark_script
    links:
      - rtmp-stream-server
    tty: true

  spark-worker-1:
    container_name: spark-worker-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/spark/spark_script
    tty: true

  spark-worker-2:
    container_name: spark-worker-2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/spark/spark_script
    tty: true

  rtmp-stream-server:
    container_name: rtmp-server
    build:
      context: .
      dockerfile: Dockerfile.rtmpserver
    ports:
      - "1935:1935"
    expose:
      - "1935"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./utils:/opt/spark/utils
    tty: true

volumes:
  spark_script:
